version: '2'
services:
    web:
        build:
            context: ./
            dockerfile: images/nginx/Dockerfile
        volumes:
            - ./app/:/var/www/app
        ports:
            - "8080:80"
        links:
            - app
    app:
        build:
            context: ./
            dockerfile: images/php/Dockerfile
        volumes:
            - ./app/:/var/www/app
        links:
            - database
            - cache
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=database"
            - "REDIS_PORT=6379"
            - "REDIS_HOST=cache"
    database:
        image: mysql:5.7
        environment:
            - "MYSQL_ROOT_PASSWORD=yse45rdx"
            - "MYSQL_DATABASE=app"
        ports:
            - "33061:3306"
    cache:
        image: redis:3.0
        ports:
            - "63791:6379"