apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: hello-world
  namespace: hello-world
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: hello-world
  chart:
    repository: https://charts.rissc.net
    name: hello-world
    version: 0.1.49
  values:
    hello-nginx:
      image: saschariedel/hello-nginx:wvfszp6i
    hello-php:
      image: saschariedel/hello-php:wvfszp6i